### ISSUE TITLE
Add contract implementation with better type support

### ISSUE THREAD

**Issue by davelange** [keep-starknet-strange/abi-wan-kanabi#10]
It would be useful to export a function to actually create contract instances with the ABI based types. This could then be used in the starknet.js and starknet-react libs, providing better type support there. This is what happens when using `wagmi`, for example.

The usage could be something like:
```ts
const contract = getContract(abi, address, account);

const bal = await contract.balanceOf... <-- IDE autocomplete, args validation, and typed return value
```
Does this make sense? I could open a PR for this feature.

**Comment by ivpavici** [comment]
hello @davelange , thanks ! @thomas-quadratic , @Riad-Quadratic or @tabaktoni will take a look and get back to you!

**Comment by tabaktoni** [comment]
Yes please, if you need help just ping me

**Comment by davelange** [comment]
Thanks @tabaktoni
I can see 2 ways of doing this: one is creating the contract instance in this lib, which would imply adding starknet as a dep here. The other is only exporting the type for contract methods, and it would be the responsibility of other libs to use it.
Which do you think would be better?

**Comment by ivpavici** [comment]
@tabaktoni ping about the question above :)
Anyway, the project got additional funds for this month so we can proceed with all relevant changes! 
cc: @thomas-quadratic

**Comment by tabaktoni** [comment]
It should be independent lib that should be used by starknetjs or other, without starknet as dep.

**Comment by davelange** [comment]
Thanks, that makes sense 👍 I'll open the PR

**Comment by haroune-mohammedi** [comment]
Is this still relevant ?
