### ISSUE TITLE
Return type key

### ISSUE THREAD

**Issue by davelange** [keep-starknet-strange/abi-wan-kanabi#12]
The `FunctionRet` type returns the value directly, for example:
```typescript
const balanceOf = erc20.balanceOf(123);
```
balanceOf type is:
```
{
    low: number;
    high: number;
}
```
But in reality it's 
```
{
   balance: {
       low: number;
       high: number;
   }
}
```
right?

I can open a PR for this.

**Comment by ivpavici** [comment]
@tabaktoni please check 🙏

**Comment by thomas-quadratic** [comment]
Hi @davelange 
Correct me if I am wrong, but this seems to be an issue with Cairo 0 contracts.
We are currently migrating to Cairo 1 with PR#9 to be merged soon, sorry for the delay.
Anyways, if this is indeed the case, we will close this issue as Cairo 0 is deprecated.

**Comment by haroune-mohammedi** [comment]
Is this still relevant ?

**Comment by davelange** [comment]
No, I'd say it can be closed
