### ISSUE TITLE
Resolve import of ABI

### ISSUE THREAD

**Issue by tabaktoni** [keep-starknet-strange/abi-wan-kanabi#4]
Currently, ABI is placed as part of https://github.com/ivpavici/abi-wan-kanabi/blob/main/test/example.ts
Issues were related to importing it.
Find a way to import it from abi.json
For implementation to work it needs to be imported as const

**Comment by thomas-quadratic** [comment]
Importing a JSON with const assertion is actually not possible in Typescript. An issue has been open for more than 3 years now on the typescript repo: https://github.com/microsoft/TypeScript/issues/32063

As a work around, at the moment, it seems that writing the abi to a typescript file is inevitable. There is a solution in the issue above, which could be included in a Makefile everytime contracts are compiled:

```bash
echo -E "declare const abi: $(cat abi.json) as const; export default abi;" > abi.d.ts
```
