### ISSUE TITLE
Strip ts files from the shipped module

### ISSUE THREAD

**Issue by arijoon** [keep-starknet-strange/abi-wan-kanabi#42]
It seems like typescript  maintainers are going down unreasonable paths: https://github.com/microsoft/TypeScript/issues/41883

This means any ts files shipped in this module are checked against tsconfig of the clients. There are some unused variables and imported but not used parameters. If possible, please strip the `index.ts` file from the published package

**Comment by adrian-gierakowski** [comment]
I don't think the issues is with typescript maintainers. Properly building the package, and distributing it with a populated dist/ dir, and `main` in package.json pointing at `dist/index.js` should fix it (btw [bin](https://github.com/keep-starknet-strange/abi-wan-kanabi/blob/f7cb9f53cc5f94475eed47a11f46406b9d745de7/package.json#L7) points at dist but it's not present in the npm pacakge). The ts files should probably not be included in the npm package.

**Comment by adrian-gierakowski** [comment]
this should https://github.com/keep-starknet-strange/abi-wan-kanabi/pull/43

I would advise testing against the [starknet](https://www.npmjs.com/package/starknet) package which seems to be the only public consumer of this one

**Comment by ivpavici** [comment]
hello, thanks! 🙏 will TAL soon!

**Comment by adrian-gierakowski** [comment]
btw. starkent package seems to be only using this package for it's [types](https://github.com/starknet-io/starknet.js/blob/98f3e7a237f72eb4c664b765888dd4e181a962d2/src/contract/interface.ts#L1C56-L1C56) so migth be good idea to ask them to use `import type` and move `abi-wan-kanabi` to `devDependencies`
