### ISSUE TITLE
Catchup with Starknet.js

### ISSUE THREAD

**Issue by haroune-mohammedi** [keep-starknet-strange/abi-wan-kanabi#68]
The goal of this issue is to make sure Abiwan is fully compatible with the latest starknet.js versions, basically make sure it supports all the newly added types, for instance:

- [ ] [`core::starknet::secp256k1::Secp256k1Point`](https://github.com/starknet-io/starknet.js/pull/985#issuecomment-2010136311) 
- [ ] [`u512`](https://github.com/starknet-io/starknet.js/pull/1022#issuecomment-2009091763)

@PhilippeR26 You're welcome to add types I missed in this issue

**Comment by PhilippeR26** [comment]
Seems good.
